baseURL = "https://schulball-grg4.at"
publishDir = "docs"
title = "Schulball grg4"
languageCode = "de-au"
defaultContentLanguage = "de"
pagination.pagerSize = "7"
theme = "spectral"
#googleAnalytics = "G-XXXXXXXXXX"

[params]
fancyTitle = "Secret Garden" # title for frontpage, may include image
copyright = "Wiedner gymnasium"
description = 'Schulball des Wiednergymnasiums und Sir Karl Popper Schule'
startbuttonText = "Termin"
startbuttonLink = "#termin"
body_is_markdown = true
custom_css = "custom.css"
#custom_sass = "bar.scss"
#images = ["path_to_social_image_for_link_previews.jpg"]

[markup.goldmark.renderer]
        unsafe = true # NOT-RECOMMENDED! FOR DEMO PURPOSE ONLY![[params.menu.main]]

url = '/'
title = "Start"

[[params.menu.main]]
url = '/sponsoren/'
title = "Sponsoren"

[[params.menu.main]]
url = '/ballabend/'
title = "Weiteres zum Ballabend"

[[params.menu.main]]
url = '/archive/'
title = "archive"

[params.two]
enable = true

[[params.two.section]]
img = "Placeholder.jpg"
img_alt = "blurry background: white/grey"
title = 'Wann: <br /> <h3>24. Mai 2025</h3>'
body = '<ul style="list-style-type: none; padding: 0; margin: 0;"><li>Einlass: 19:30<li/><li>Eroeffnung: 20:30 <li/><li>Ende: 3:00<li/><li><a href="">Link zum Programm</a><li/><ul/>'

[[params.two.section]]
img = "Placeholder.jpg"
title = 'Wo:'
body = '<ul style="list-style-type: none; padding: 0; margin: 0;"><li style="margin: 0;"><b class="content">Arcotel Wimberger</b></li><li style="margin: 0;"><b class="content">Neubauguertel 34-36, 1070 Wien</b></li><li style="margin: 0;"><h3>Anreise:</h3></li><li style="margin: 0;"><b class="content">Westbahnhof</b></li><li style="margin: 0;"><b class="content">U6/U3/S-Bahn</b></li><li style="margin: 0;"><b class="content">Urban-Loritz-Platz</b></li><li style="margin: 0;"><b class="content">18/6 Strassenbahn</b></li><li style="margin: 0;"><b class="content">N49/N8 Bus</b></li></ul>'

[[params.two.section]]
img = "Eintrittskarte.svg"
title = 'Tickets'
body = '<h3>Preise:</h3><ul style="list-style-type: none; padding: 0; margin: 0;"><li>Schueler*innen: 35 EURO <li/><li>Erwachsene: 50 EURO <li/><li>Tische: 10 Plaetze: 150 EURO <li/><li><a href="">Kaufen</a><li/><ul/>'

[params.cta]
enable = true
title = "Regeln"
body = "Mit dem Kauf Stimmen Sie den von uns aufgestellten Regeln zu."

[[params.cta.link]]
href = "/ballabend/"
text = "Ballregeln"
special = true

[params.contact]
enable = true
title = "Tickets kaufen"
body = "Leave us a message."
address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
email = "nospam@example.com"
subject = "Karten Kaufen"
formspree_form_id = "example_invalid"

[params.social]
instagram = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"

[languages.de]
weight = 0
languageName = "Deutsch"
