baseURL = "/"
title = "Schulball grg4"
languageCode = "de-au"
defaultContentLanguage = "de"
pagination.pagerSize = "7"
theme = "spectral"
#googleAnalytics = "G-XXXXXXXXXX"

[params]
fancyTitle = "Secret Guarden" # title for frontpage, may include image
copyright = "Wiedner gymnasium"
description = 'Schulball des Wiednergymnasiums und Sir Karl Popper Schule'
startbuttonText = "Termin"
startbuttonLink = "#termin"
body_is_markdown = true
custom_css = "custom.css"
#custom_sass = "bar.scss"
#images = ["path_to_social_image_for_link_previews.jpg"]

[markup.goldmark.renderer]
        unsafe = true # NOT-RECOMMENDED! FOR DEMO PURPOSE ONLY![[params.menu.main]]

url = '/'
title = "Start"

[[params.menu.main]]
url = '/sponsoren/'
title = "Sponsoren"

[[params.menu.main]]
url = '/ballabend/'
title = "Weiteres zum Ballabend"

[[params.menu.main]]
url = '/archive/'
title = "archive"

[params.two]
enable = true

[[params.two.section]]
img = "Placeholder.jpg"
img_alt = "blurry background: white/grey"
title = 'Wann: <br /> <h3>24. Mai 2025</h3>'
body = 'Einlass: 19:30<br />Eroeffnung: 20:30 <br />Ende: 3:00<br /><a href="">Link zum Programm</a>'

[[params.two.section]]
img = "Placeholder.jpg"
title = 'Wo:'
body = '<b class="content">Arcotel Wimberger</b> <br /><b class="content">Neubauguertel 34-36, 1070 Wien</b><br /><h3>Anreise:</h3><b class="content">Westbahnhof<br/></b><b class="content">U6/U3/S-Bahn</b><br/><br/><b class="content">Urban-Loritz-Platz</b><br/><b class="content">18/6 Strassenbahn</b><br/><b class="content">N49/N8 Bus</b>'

[[params.two.section]]
img = "Eintrittskarte.svg"
title = 'Tickets'
body = '<h3>Preise:</h3> <br />Schueler*innen: 35 EURO<br />Erwachsene: 50 EURO<br />Tische: 10 Plaetze: 150 EURO<br /><a href="">Kaufen</a>'

[params.cta]
enable = true
title = "Regeln"
body = "Mit dem Kauf Stimmen Sie den von uns aufgestellten Regeln zu."

[[params.cta.link]]
href = "#"
text = "Ballregeln"
special = true

[params.contact]
enable = true
title = "Tickets kaufen"
body = "Leave us a message."
address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
email = "nospam@example.com"
subject = "Karten Kaufen"
formspree_form_id = "example_invalid"

[params.social]
instagram = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"

[languages.de]
weight = 0
languageName = "Deutsch"
